tasks_file_path: "data/preprocessed/kramabench/dev/dev_all/tasks.pkl"  # kramabench/dev/dev/tasks.pkl
subset_file_path: null
db_root_dir: "data/kramabench/dev/dev_databases"
n_processes: 32
max_rollout_steps: 24
max_depth: 16
exploration_constant: 1.414
save_root_dir: "results/deepseek-chat/kramabench/dev" ### remember to change the dir name!!
mcts_model_kwargs:
    model: "deepseek-chat"  # only support n=1, not able to be used in alphasql
    n: 3
    top_p: 0.8
    max_tokens: 4096
    temperature: 0.8
    n_strategy: "single"
reward_model_kwargs: null   