tasks_file_path: "data/preprocessed/bird/dev/dev/tasks.pkl"
subset_file_path: null #"data/bird/dev/dev_databases/codebase_community/" 
db_root_dir: "data/bird/dev/dev_databases"
n_processes: 30
max_rollout_steps: 24
max_depth: 16
exploration_constant: 1.414
save_root_dir: "results/Qwen2.5-Coder-7B-Instruct/bird/dev"
mcts_model_kwargs:
    model: "Qwen2.5-Coder-7B-Instruct"      #"qwen7b-coder" #"qwen2.5-coder:7b-instruct"
    n: 3
    top_p: 0.8
    max_tokens: 4096
    temperature: 0.8
    n_strategy: "single"
reward_model_kwargs: null 
